---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  # assumes there will be a Secret named ente-museum-secrets
  - target:
      kind: Deployment
      name: ente-museum
    path: add-volume.patch.yaml