---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ente-database
spec:
  instances: 2
  storage:
    storageClass: nfs-db
    size: 10Gi
  walStorage:
    storageClass: local-path
    size: 10Gi
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-backups
      endpointURL: https://f061e3d9b3cb2a466cdbef9ea19cee24.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: ente-database-s3
          key: accessKey
        secretAccessKey:
          name: ente-database-s3
          key: secretKey
      data:
        compression: gzip
        encryption: AES256
      wal:
        compression: gzip
        maxParallel: 8
        encryption: AES256
    retentionPolicy: 60d
