---
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: ENTE_API_ORIGIN
    value: https://api.ente.arthur.computer
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: ENTE_ALBUMS_ORIGIN
    value: https://albums.ente.arthur.computer