---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ente-museum-secrets
  labels:
    app.kubernetes.io/component: api-server
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/component: api-server
      engineVersion: v2
      data:
        credentials.yaml: |
          s3:
            b2-eu-cen:
              key: {{ .s3AccessKey }}
              secret: {{ .s3SecretKey }}
              endpoint: {{ .s3Endpoint }}
          key:
            encryption: {{ .keyEncryption }}
            hash: {{ .keyHash }}
          jwt:
            secret: {{ .jwt }}
          smtp:
            username: {{ .smtpUser }}
            password: {{ .smtpPass }}
          internal:
            admin: {{ .adminId }}
  data:
    # s3 values
    - secretKey: s3AccessKey
      remoteRef:
        key: "R2 - ente/access key"
    - secretKey: s3SecretKey
      remoteRef:
        key: "R2 - ente/secret key"
    - secretKey: s3Endpoint
      remoteRef:
        key: "R2 - ente/endpoint"
    # key values
    - secretKey: keyEncryption
      remoteRef:
        key: "Ente Secrets/key"
    - secretKey: keyHash
      remoteRef:
        key: "Ente Secrets/hash"
    # jwt value
    - secretKey: jwt
      remoteRef:
        key: "Ente Secrets/jwt"
    # smtp values
    - secretKey: smtpUser
      remoteRef:
        key: "Fastmail - ente/SMTP/username"
    - secretKey: smtpPass
      remoteRef:
        key: "Fastmail - ente/SMTP/password"
    # internal values
    - secretKey: adminId
      remoteRef:
        key: "ente - admin/user id"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ente-database-s3
  labels:
    app.kubernetes.io/component: database
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/component: database
  data:
    - secretKey: accessKey
      remoteRef:
        key: "R2 - cnpg/access key"
    - secretKey: secretKey
      remoteRef:
        key: "R2 - cnpg/secret key"
