---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: ente
      app.kubernetes.io/part-of: ente
    includeSelectors: true
    includeTemplates: true
  - pairs:
      app.kubernetes.io/version: "20250901"

# we'll handle this in ArgoCD
# namespace: ente

resources:
  - ../../base
  - external-secret.yaml
  - object-store.yaml
  - scheduled-backup.yaml

components:
  - ../../components/cloudnativepg
  - ../../components/museum-config
  - ../../components/museum-secrets
  - ../../components/external-secrets
  - ../../components/replace-hostname
  - ../../components/autoscaler

patches:
  - target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: ente-database
    path: cluster.patch.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ente
    path: ingress.patch.yaml

configMapGenerator:
  - name: ente-vars
    literals:
      - hostname=arthur.computer
  - name: ente-museum-config
    files:
      - museum.yaml
    options:
      labels:
        app.kubernetes.io/component: api-server
