---
labels:
  - kind: ExternalSecret
    path: spec/target/template/metadata/labels
    create: true

commonLabels:
  - kind: ExternalSecret
    path: spec/target/template/metadata/labels
    create: true

nameReference:
  - kind: ExternalSecret
    fieldSpecs:
      - kind: Secret
        path: spec/target/template/name
