---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

labels:
  - pairs:
      app.kubernetes.io/name: ente
      app.kubernetes.io/part-of: ente

resources:
  - cluster.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ente-museum
    path: deployment.patch.yaml
