apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: ente-database-base
  namespace: ente
spec:
  cluster:
    name: ente-database
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
