---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/ente-io/server
    newTag: 613c6a96390d7a624cf30b946955705d632423cc
  - name: ghcr.io/ente-io/web
    newTag: 781ac5d269908e311a28010644a46c5bc11f23f0

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
