---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: ghcr.io/ente-io/server
    newTag: 1119f7abf19c529f29dc7cad7bf249ce35f38a05
  - name: ghcr.io/ente-io/web
    newTag: 19219bdcb6cff3b8c6a70d51a3343080ec7619ea

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
